### ISSUE TITLE
Add dotgen to Stackage

### ISSUE THREAD

**Issue by kaoskorobase** [ku-fpg/dotgen#2]
Would you be interested in adding `dotgen` to [Stackage](https://www.stackage.org/)? The upside is that your package will be regularly built and tested against its dependencies. A possible downside is that you will get occasional build failure reports that will have to be addressed.

Adding a package is not very complicated: https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package

**Comment by andygill** [comment]
Thanks for the heads up. I'll have a look at some point over the next couple of weeks.

**Comment by RyanGlScott** [comment]
@andygill, I'd be happy to add anything you want to see on Stackage. Are there any other packages besides `dotgen` you'd want included? Currently, the only @ku-fpg packages at the moment are `blank-canvas` and its dependencies (i.e., `kansas-comet`).

Another important question: would you want to be listed under the username map for @ku-fpg? ([Currently, I'm the only one.](https://github.com/fpco/stackage/blob/029988ca440b9948f2daf37ec172083ddb458f9b/build-constraints.yaml#L2586-L2587)) If you do, you will receive an e-mail every time one of the @ku-fpg packages' dependencies become out-of-date on Stackage. You may view this as a good or bad thing :)

**Comment by RyanGlScott** [comment]
I added myself as the Stackage maintainer for this package a while ago (see commercialhaskell/stackage@ea928b0bc), so this should no longer be an issue.
